### ISSUE TITLE
The binding property in NavFragment could be simplified

### ISSUE THREAD

**Issue by stewemetal** [khongi/crypto-info#58]
https://github.com/khongi/crypto-info/blob/361d999db4dc4965049c4ede4580f9537bd4cc03/app/src/main/java/com/thiosin/cryptoinfo/ui/util/NavFragment.kt#L17

Like this:

```kotlin
lateinit var binding: B
        private set
```

**Comment by stewemetal** [comment]
Scratch that, I saw the official documentation... :/

**Comment by stewemetal** [comment]
Well, actually it can be simplified:

```kotlin
protected var binding: B? = null
        private set
```

I would definitely avoid using `!!` when reading this porperty, because using it would lead to a library-related (and not app related) crash.

**Comment by khongi** [comment]
Simplifying the property in this manner would mean, accessing the property in the Fragments needs `?. `, so I kept the val version.
However I replaced the `!!` with `?: throw`

**Comment by khongi** [comment]
https://youtrack.jetbrains.com/issue/KT-14663
